# Generated by Django 4.2.1 on 2023-05-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlight',
            name='campus',
            field=models.CharField(choices=[('oye', 'Oye'), ('ikole', 'Ikole')], default='Oye', max_length=10, verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='spotlight',
            name='department',
            field=models.CharField(default='Something', max_length=50, verbose_name='Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotlight',
            name='faculty',
            field=models.CharField(default='Something', max_length=50, verbose_name='Faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotlight',
            name='favorite_bible_verse',
            field=models.CharField(default='asas', help_text="e.g. 'Matt 15 v 12'", max_length=20, verbose_name='Favourite Bible verse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spotlight',
            name='favorite_quote',
            field=models.CharField(default='ddsd', help_text="Type 'None' if this field is not provided.", max_length=225, verbose_name='Favourite Quote'),
            preserve_default=False,
        ),
    ]
