# Generated by Django 4.2.1 on 2023-05-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_spotlight_campus_spotlight_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdaycelebrant',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='spotlight',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='birthdaycelebrant',
            name='birthdate',
            field=models.CharField(help_text='Just the day and the month; in the formart `DD-MM`.', max_length=20, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='birthdate',
            field=models.CharField(help_text='Just the day and the month; in the formart `DD-MM`.', max_length=20, verbose_name='Date of birth'),
        ),
    ]
