# Generated by Django 4.2.1 on 2023-05-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_birthdate_birthdaycelebrant_birthday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotlight',
            options={'ordering': ('-created_at',)},
        ),
    ]
